/*
 * jwt_example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: mosorio@isi.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"SecretGet",
			strings.ToUpper("Get"),
			"/secret",
			c.SecretGet,
		},
		{
			"UserLoginPost",
			strings.ToUpper("Post"),
			"/user/login",
			c.UserLoginPost,
		},
	}
}

// SecretGet - Show a secret
func (c *DefaultApiController) SecretGet(w http.ResponseWriter, r *http.Request) { 
	result, err := c.service.SecretGet()
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// UserLoginPost - 
func (c *DefaultApiController) UserLoginPost(w http.ResponseWriter, r *http.Request) { 
	user := &User{}
	if err := json.NewDecoder(r.Body).Decode(&user); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.UserLoginPost(*user)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
