/*
 * jwt_example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: mosorio@isi.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// SecretGet - Show a secret
func SecretGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UserLoginPost - 
func UserLoginPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
